package entities;

// Generated Apr 7, 2016 1:58:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Capdo generated by hbm2java
 */
@Entity
@Table(name = "Capdo", catalog = "Tracnghiem")
public class Capdo implements java.io.Serializable {

	private int maCd;
	private Cauhoi cauhoi;
	private String tenCd;
	private String ghichu;
	private Set<Diem> diems = new HashSet<Diem>(0);

	public Capdo() {
	}

	public Capdo(Cauhoi cauhoi, String tenCd) {
		this.cauhoi = cauhoi;
		this.tenCd = tenCd;
	}

	public Capdo(Cauhoi cauhoi, String tenCd, String ghichu, Set<Diem> diems) {
		this.cauhoi = cauhoi;
		this.tenCd = tenCd;
		this.ghichu = ghichu;
		this.diems = diems;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "cauhoi"))
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaCd", unique = true, nullable = false)
	public int getMaCd() {
		return this.maCd;
	}

	public void setMaCd(int maCd) {
		this.maCd = maCd;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Cauhoi getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(Cauhoi cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "TenCd", nullable = false, length = 50)
	public String getTenCd() {
		return this.tenCd;
	}

	public void setTenCd(String tenCd) {
		this.tenCd = tenCd;
	}

	@Column(name = "Ghichu", length = 50)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capdo")
	public Set<Diem> getDiems() {
		return this.diems;
	}

	public void setDiems(Set<Diem> diems) {
		this.diems = diems;
	}

}
