package entities;

// Generated Apr 7, 2016 1:58:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cauhoi generated by hbm2java
 */
@Entity
@Table(name = "Cauhoi", catalog = "Tracnghiem")
public class Cauhoi implements java.io.Serializable {

	private int maCh;
	private Monhoc monhoc;
	private String cauhoi;
	private String dapan;
	private Integer maCd;
	private String ghichu;
	private Capdo capdo;

	public Cauhoi() {
	}

	public Cauhoi(int maCh) {
		this.maCh = maCh;
	}

	public Cauhoi(int maCh, Monhoc monhoc, String cauhoi, String dapan,
			Integer maCd, String ghichu, Capdo capdo) {
		this.maCh = maCh;
		this.monhoc = monhoc;
		this.cauhoi = cauhoi;
		this.dapan = dapan;
		this.maCd = maCd;
		this.ghichu = ghichu;
		this.capdo = capdo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaCh", unique = true, nullable = false)
	public int getMaCh() {
		return this.maCh;
	}

	public void setMaCh(int maCh) {
		this.maCh = maCh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaMh")
	public Monhoc getMonhoc() {
		return this.monhoc;
	}

	public void setMonhoc(Monhoc monhoc) {
		this.monhoc = monhoc;
	}

	@Column(name = "Cauhoi", length = 550)
	public String getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(String cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "Dapan", length = 50)
	public String getDapan() {
		return this.dapan;
	}

	public void setDapan(String dapan) {
		this.dapan = dapan;
	}

	@Column(name = "MaCd")
	public Integer getMaCd() {
		return this.maCd;
	}

	public void setMaCd(Integer maCd) {
		this.maCd = maCd;
	}

	@Column(name = "Ghichu", length = 50)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "cauhoi")
	public Capdo getCapdo() {
		return this.capdo;
	}

	public void setCapdo(Capdo capdo) {
		this.capdo = capdo;
	}

}
