package entities;

// Generated Apr 7, 2016 1:58:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiemId generated by hbm2java
 */
@Embeddable
public class DiemId implements java.io.Serializable {

	private int maTk;
	private int maUser;
	private Date ngaythi;
	private int maCd;
	private int maMh;
	private String diem;
	private String ghichu;

	public DiemId() {
	}

	public DiemId(int maTk, int maUser, Date ngaythi, int maCd, int maMh,
			String diem) {
		this.maTk = maTk;
		this.maUser = maUser;
		this.ngaythi = ngaythi;
		this.maCd = maCd;
		this.maMh = maMh;
		this.diem = diem;
	}

	public DiemId(int maTk, int maUser, Date ngaythi, int maCd, int maMh,
			String diem, String ghichu) {
		this.maTk = maTk;
		this.maUser = maUser;
		this.ngaythi = ngaythi;
		this.maCd = maCd;
		this.maMh = maMh;
		this.diem = diem;
		this.ghichu = ghichu;
	}

	@Column(name = "MaTk", nullable = false)
	public int getMaTk() {
		return this.maTk;
	}

	public void setMaTk(int maTk) {
		this.maTk = maTk;
	}

	@Column(name = "MaUser", nullable = false)
	public int getMaUser() {
		return this.maUser;
	}

	public void setMaUser(int maUser) {
		this.maUser = maUser;
	}

	@Column(name = "Ngaythi", nullable = false, length = 23)
	public Date getNgaythi() {
		return this.ngaythi;
	}

	public void setNgaythi(Date ngaythi) {
		this.ngaythi = ngaythi;
	}

	@Column(name = "MaCd", nullable = false)
	public int getMaCd() {
		return this.maCd;
	}

	public void setMaCd(int maCd) {
		this.maCd = maCd;
	}

	@Column(name = "MaMh", nullable = false)
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}

	@Column(name = "Diem", nullable = false, length = 50)
	public String getDiem() {
		return this.diem;
	}

	public void setDiem(String diem) {
		this.diem = diem;
	}

	@Column(name = "Ghichu", length = 50)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiemId))
			return false;
		DiemId castOther = (DiemId) other;

		return (this.getMaTk() == castOther.getMaTk())
				&& (this.getMaUser() == castOther.getMaUser())
				&& ((this.getNgaythi() == castOther.getNgaythi()) || (this
						.getNgaythi() != null && castOther.getNgaythi() != null && this
						.getNgaythi().equals(castOther.getNgaythi())))
				&& (this.getMaCd() == castOther.getMaCd())
				&& (this.getMaMh() == castOther.getMaMh())
				&& ((this.getDiem() == castOther.getDiem()) || (this.getDiem() != null
						&& castOther.getDiem() != null && this.getDiem()
						.equals(castOther.getDiem())))
				&& ((this.getGhichu() == castOther.getGhichu()) || (this
						.getGhichu() != null && castOther.getGhichu() != null && this
						.getGhichu().equals(castOther.getGhichu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaTk();
		result = 37 * result + this.getMaUser();
		result = 37 * result
				+ (getNgaythi() == null ? 0 : this.getNgaythi().hashCode());
		result = 37 * result + this.getMaCd();
		result = 37 * result + this.getMaMh();
		result = 37 * result
				+ (getDiem() == null ? 0 : this.getDiem().hashCode());
		result = 37 * result
				+ (getGhichu() == null ? 0 : this.getGhichu().hashCode());
		return result;
	}

}
