package entities;

// Generated Apr 7, 2016 1:58:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name = "Monhoc", catalog = "Tracnghiem")
public class Monhoc implements java.io.Serializable {

	private int maMh;
	private String tenMon;
	private String maCd;
	private String ghichu;
	private Set<Diem> diems = new HashSet<Diem>(0);
	private Set<Cauhoi> cauhois = new HashSet<Cauhoi>(0);

	public Monhoc() {
	}

	public Monhoc(int maMh) {
		this.maMh = maMh;
	}

	public Monhoc(int maMh, String tenMon, String maCd, String ghichu,
			Set<Diem> diems, Set<Cauhoi> cauhois) {
		this.maMh = maMh;
		this.tenMon = tenMon;
		this.maCd = maCd;
		this.ghichu = ghichu;
		this.diems = diems;
		this.cauhois = cauhois;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaMh", unique = true, nullable = false)
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}

	@Column(name = "TenMon", length = 50)
	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	@Column(name = "MaCd", length = 10)
	public String getMaCd() {
		return this.maCd;
	}

	public void setMaCd(String maCd) {
		this.maCd = maCd;
	}

	@Column(name = "Ghichu", length = 50)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monhoc")
	public Set<Diem> getDiems() {
		return this.diems;
	}

	public void setDiems(Set<Diem> diems) {
		this.diems = diems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monhoc")
	public Set<Cauhoi> getCauhois() {
		return this.cauhois;
	}

	public void setCauhois(Set<Cauhoi> cauhois) {
		this.cauhois = cauhois;
	}

}
