package entities;

// Generated Apr 7, 2016 1:58:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "Nguoichoi", catalog = "Tracnghiem")
@XmlRootElement
public class Nguoichoi implements java.io.Serializable {

	private int maUser;
	private String tenUser;
	private Date ngaysinh;
	private String email;
	private String tenDn;
	private String matkhau;
	private String ghichu;
	private Set<Diem> diems = new HashSet<Diem>(0);

	public Nguoichoi() {
	}

	public Nguoichoi(int maUser) {
		this.maUser = maUser;
	}

	public Nguoichoi(int maUser, String tenUser, Date ngaysinh, String email,
			String tenDn, String matkhau, String ghichu, Set<Diem> diems) {
		this.maUser = maUser;
		this.tenUser = tenUser;
		this.ngaysinh = ngaysinh;
		this.email = email;
		this.tenDn = tenDn;
		this.matkhau = matkhau;
		this.ghichu = ghichu;
		this.diems = diems;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaUser", unique = true, nullable = false)
	public int getMaUser() {
		return this.maUser;
	}

	public void setMaUser(int maUser) {
		this.maUser = maUser;
	}

	@Column(name = "TenUser", length = 50)
	public String getTenUser() {
		return this.tenUser;
	}

	public void setTenUser(String tenUser) {
		this.tenUser = tenUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngaysinh", length = 23)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TenDn", length = 50)
	public String getTenDn() {
		return this.tenDn;
	}

	public void setTenDn(String tenDn) {
		this.tenDn = tenDn;
	}

	@Column(name = "Matkhau", length = 50)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Diem> getDiems() {
		return this.diems;
	}

	public void setDiems(Set<Diem> diems) {
		this.diems = diems;
	}

}
