package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhatkyLh generated by hbm2java
 */
@Entity
@Table(name = "NhatkyLH", catalog = "Sunshine_final")
public class NhatkyLh implements java.io.Serializable {

	private int maNk;
	private Giaovien giaovien;
	private Lophoc lophoc;
	private Date ngayghi;
	private String noidung;

	public NhatkyLh() {
	}

	public NhatkyLh(int maNk, Giaovien giaovien, Lophoc lophoc, Date ngayghi) {
		this.maNk = maNk;
		this.giaovien = giaovien;
		this.lophoc = lophoc;
		this.ngayghi = ngayghi;
	}

	public NhatkyLh(int maNk, Giaovien giaovien, Lophoc lophoc, Date ngayghi,
			String noidung) {
		this.maNk = maNk;
		this.giaovien = giaovien;
		this.lophoc = lophoc;
		this.ngayghi = ngayghi;
		this.noidung = noidung;
	}

	@Id
	@Column(name = "MaNK", unique = true, nullable = false)
	public int getMaNk() {
		return this.maNk;
	}

	public void setMaNk(int maNk) {
		this.maNk = maNk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGV", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLop", nullable = false)
	public Lophoc getLophoc() {
		return this.lophoc;
	}

	public void setLophoc(Lophoc lophoc) {
		this.lophoc = lophoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayghi", nullable = false, length = 23)
	public Date getNgayghi() {
		return this.ngayghi;
	}

	public void setNgayghi(Date ngayghi) {
		this.ngayghi = ngayghi;
	}

	@Column(name = "Noidung", length = 250)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
