package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TonghopNxt generated by hbm2java
 */
@Entity
@Table(name = "TonghopNXT", catalog = "Sunshine_final")
public class TonghopNxt implements java.io.Serializable {

	private int maTh;
	private Kho kho;
	private Hanghoa hanghoa;
	private Integer thang;
	private Integer nam;
	private String dvt;
	private Integer dongia;
	private Integer tondauky;
	private Integer thanhtiendauky;
	private Integer nhap;
	private Integer tongtiennhap;
	private Integer xuat;
	private Integer tongtienxuat;
	private Integer toncuoiky;
	private Integer thanhtiencuoiky;
	private String ghichu;

	public TonghopNxt() {
	}

	public TonghopNxt(int maTh) {
		this.maTh = maTh;
	}

	public TonghopNxt(int maTh, Kho kho, Hanghoa hanghoa, Integer thang,
			Integer nam, String dvt, Integer dongia, Integer tondauky,
			Integer thanhtiendauky, Integer nhap, Integer tongtiennhap,
			Integer xuat, Integer tongtienxuat, Integer toncuoiky,
			Integer thanhtiencuoiky, String ghichu) {
		this.maTh = maTh;
		this.kho = kho;
		this.hanghoa = hanghoa;
		this.thang = thang;
		this.nam = nam;
		this.dvt = dvt;
		this.dongia = dongia;
		this.tondauky = tondauky;
		this.thanhtiendauky = thanhtiendauky;
		this.nhap = nhap;
		this.tongtiennhap = tongtiennhap;
		this.xuat = xuat;
		this.tongtienxuat = tongtienxuat;
		this.toncuoiky = toncuoiky;
		this.thanhtiencuoiky = thanhtiencuoiky;
		this.ghichu = ghichu;
	}

	@Id
	@Column(name = "MaTh", unique = true, nullable = false)
	public int getMaTh() {
		return this.maTh;
	}

	public void setMaTh(int maTh) {
		this.maTh = maTh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Makho")
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mahang")
	public Hanghoa getHanghoa() {
		return this.hanghoa;
	}

	public void setHanghoa(Hanghoa hanghoa) {
		this.hanghoa = hanghoa;
	}

	@Column(name = "Thang")
	public Integer getThang() {
		return this.thang;
	}

	public void setThang(Integer thang) {
		this.thang = thang;
	}

	@Column(name = "Nam")
	public Integer getNam() {
		return this.nam;
	}

	public void setNam(Integer nam) {
		this.nam = nam;
	}

	@Column(name = "Dvt", length = 50)
	public String getDvt() {
		return this.dvt;
	}

	public void setDvt(String dvt) {
		this.dvt = dvt;
	}

	@Column(name = "Dongia")
	public Integer getDongia() {
		return this.dongia;
	}

	public void setDongia(Integer dongia) {
		this.dongia = dongia;
	}

	@Column(name = "Tondauky")
	public Integer getTondauky() {
		return this.tondauky;
	}

	public void setTondauky(Integer tondauky) {
		this.tondauky = tondauky;
	}

	@Column(name = "Thanhtiendauky")
	public Integer getThanhtiendauky() {
		return this.thanhtiendauky;
	}

	public void setThanhtiendauky(Integer thanhtiendauky) {
		this.thanhtiendauky = thanhtiendauky;
	}

	@Column(name = "Nhap")
	public Integer getNhap() {
		return this.nhap;
	}

	public void setNhap(Integer nhap) {
		this.nhap = nhap;
	}

	@Column(name = "Tongtiennhap")
	public Integer getTongtiennhap() {
		return this.tongtiennhap;
	}

	public void setTongtiennhap(Integer tongtiennhap) {
		this.tongtiennhap = tongtiennhap;
	}

	@Column(name = "Xuat")
	public Integer getXuat() {
		return this.xuat;
	}

	public void setXuat(Integer xuat) {
		this.xuat = xuat;
	}

	@Column(name = "Tongtienxuat")
	public Integer getTongtienxuat() {
		return this.tongtienxuat;
	}

	public void setTongtienxuat(Integer tongtienxuat) {
		this.tongtienxuat = tongtienxuat;
	}

	@Column(name = "Toncuoiky")
	public Integer getToncuoiky() {
		return this.toncuoiky;
	}

	public void setToncuoiky(Integer toncuoiky) {
		this.toncuoiky = toncuoiky;
	}

	@Column(name = "Thanhtiencuoiky")
	public Integer getThanhtiencuoiky() {
		return this.thanhtiencuoiky;
	}

	public void setThanhtiencuoiky(Integer thanhtiencuoiky) {
		this.thanhtiencuoiky = thanhtiencuoiky;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
