package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BoSp generated by hbm2java
 */
@Entity
@Table(name = "BoSP", catalog = "Sunshine_final")
public class BoSp implements java.io.Serializable {

	private int maBo;
	private String tenBo;
	private String ghichu;
	private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);

	public BoSp() {
	}

	public BoSp(int maBo) {
		this.maBo = maBo;
	}

	public BoSp(int maBo, String tenBo, String ghichu, Set<Hanghoa> hanghoas) {
		this.maBo = maBo;
		this.tenBo = tenBo;
		this.ghichu = ghichu;
		this.hanghoas = hanghoas;
	}

	@Id
	@Column(name = "MaBo", unique = true, nullable = false)
	public int getMaBo() {
		return this.maBo;
	}

	public void setMaBo(int maBo) {
		this.maBo = maBo;
	}

	@Column(name = "TenBo", length = 50)
	public String getTenBo() {
		return this.tenBo;
	}

	public void setTenBo(String tenBo) {
		this.tenBo = tenBo;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boSp")
	public Set<Hanghoa> getHanghoas() {
		return this.hanghoas;
	}

	public void setHanghoas(Set<Hanghoa> hanghoas) {
		this.hanghoas = hanghoas;
	}

}
