package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChitietLop generated by hbm2java
 */
@Entity
@Table(name = "ChitietLop", catalog = "Sunshine_final")
public class ChitietLop implements java.io.Serializable {

	private int maCtNkLh;
	private Hocsinh hocsinh;
	private Lophoc lophoc;
	private int thang;
	private int nam;
	private int trangthai;
	private String ghichu;

	public ChitietLop() {
	}

	public ChitietLop(int maCtNkLh, Hocsinh hocsinh, Lophoc lophoc, int thang,
			int nam, int trangthai) {
		this.maCtNkLh = maCtNkLh;
		this.hocsinh = hocsinh;
		this.lophoc = lophoc;
		this.thang = thang;
		this.nam = nam;
		this.trangthai = trangthai;
	}

	public ChitietLop(int maCtNkLh, Hocsinh hocsinh, Lophoc lophoc, int thang,
			int nam, int trangthai, String ghichu) {
		this.maCtNkLh = maCtNkLh;
		this.hocsinh = hocsinh;
		this.lophoc = lophoc;
		this.thang = thang;
		this.nam = nam;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
	}

	@Id
	@Column(name = "MaCtNkLh", unique = true, nullable = false)
	public int getMaCtNkLh() {
		return this.maCtNkLh;
	}

	public void setMaCtNkLh(int maCtNkLh) {
		this.maCtNkLh = maCtNkLh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaHs", nullable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLop", nullable = false)
	public Lophoc getLophoc() {
		return this.lophoc;
	}

	public void setLophoc(Lophoc lophoc) {
		this.lophoc = lophoc;
	}

	@Column(name = "Thang", nullable = false)
	public int getThang() {
		return this.thang;
	}

	public void setThang(int thang) {
		this.thang = thang;
	}

	@Column(name = "Nam", nullable = false)
	public int getNam() {
		return this.nam;
	}

	public void setNam(int nam) {
		this.nam = nam;
	}

	@Column(name = "Trangthai", nullable = false)
	public int getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(int trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
