package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Giaovien generated by hbm2java
 */
@Entity
@Table(name = "Giaovien", catalog = "Sunshine_final")
public class Giaovien implements java.io.Serializable {

	private int maGv;
	private Nhom nhom;
	private String hoten;
	private String ten;
	private String gioitinh;
	private Date namsinh;
	private String dienthoai;
	private String email;
	private String diachi;
	private Date ngayvao;
	private String chucvu;
	private Double mucluong;
	private String tenDn;
	private String matkhau;
	private String noilamviec;
	private String trangthai;
	private String ghichu;
	private byte[] image;
	private Set<Xuatkho> xuatkhos = new HashSet<Xuatkho>(0);
	private Set<Nhapkho> nhapkhos = new HashSet<Nhapkho>(0);
	private Set<NhatkyHang> nhatkyHangs = new HashSet<NhatkyHang>(0);
	private Set<NhatkyLh> nhatkyLhs = new HashSet<NhatkyLh>(0);
	private Set<Lophoc> lophocs = new HashSet<Lophoc>(0);
	private Set<Nhatky> nhatkies = new HashSet<Nhatky>(0);
	private Set<NhapkhoNb> nhapkhoNbs = new HashSet<NhapkhoNb>(0);
	private Set<XuatkhoNb> xuatkhoNbs = new HashSet<XuatkhoNb>(0);
	private Set<Nhaplai> nhaplais = new HashSet<Nhaplai>(0);
	private Set<NhatkyGv> nhatkyGvs = new HashSet<NhatkyGv>(0);

	public Giaovien() {
	}

	public Giaovien(int maGv) {
		this.maGv = maGv;
	}

	public Giaovien(int maGv, Nhom nhom, String hoten, String ten,
			String gioitinh, Date namsinh, String dienthoai, String email,
			String diachi, Date ngayvao, String chucvu, Double mucluong,
			String tenDn, String matkhau, String noilamviec, String trangthai,
			String ghichu, byte[] image, Set<Xuatkho> xuatkhos,
			Set<Nhapkho> nhapkhos, Set<NhatkyHang> nhatkyHangs,
			Set<NhatkyLh> nhatkyLhs, Set<Lophoc> lophocs, Set<Nhatky> nhatkies,
			Set<NhapkhoNb> nhapkhoNbs, Set<XuatkhoNb> xuatkhoNbs,
			Set<Nhaplai> nhaplais, Set<NhatkyGv> nhatkyGvs) {
		this.maGv = maGv;
		this.nhom = nhom;
		this.hoten = hoten;
		this.ten = ten;
		this.gioitinh = gioitinh;
		this.namsinh = namsinh;
		this.dienthoai = dienthoai;
		this.email = email;
		this.diachi = diachi;
		this.ngayvao = ngayvao;
		this.chucvu = chucvu;
		this.mucluong = mucluong;
		this.tenDn = tenDn;
		this.matkhau = matkhau;
		this.noilamviec = noilamviec;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
		this.image = image;
		this.xuatkhos = xuatkhos;
		this.nhapkhos = nhapkhos;
		this.nhatkyHangs = nhatkyHangs;
		this.nhatkyLhs = nhatkyLhs;
		this.lophocs = lophocs;
		this.nhatkies = nhatkies;
		this.nhapkhoNbs = nhapkhoNbs;
		this.xuatkhoNbs = xuatkhoNbs;
		this.nhaplais = nhaplais;
		this.nhatkyGvs = nhatkyGvs;
	}

	@Id
	@Column(name = "MaGV", unique = true, nullable = false)
	public int getMaGv() {
		return this.maGv;
	}

	public void setMaGv(int maGv) {
		this.maGv = maGv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNhom")
	public Nhom getNhom() {
		return this.nhom;
	}

	public void setNhom(Nhom nhom) {
		this.nhom = nhom;
	}

	@Column(name = "Hoten", length = 50)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "Ten", length = 50)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "Gioitinh", length = 10)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Namsinh", length = 23)
	public Date getNamsinh() {
		return this.namsinh;
	}

	public void setNamsinh(Date namsinh) {
		this.namsinh = namsinh;
	}

	@Column(name = "Dienthoai", length = 50)
	public String getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(String dienthoai) {
		this.dienthoai = dienthoai;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Diachi", length = 500)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayvao", length = 23)
	public Date getNgayvao() {
		return this.ngayvao;
	}

	public void setNgayvao(Date ngayvao) {
		this.ngayvao = ngayvao;
	}

	@Column(name = "Chucvu", length = 50)
	public String getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(String chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "Mucluong", precision = 15, scale = 0)
	public Double getMucluong() {
		return this.mucluong;
	}

	public void setMucluong(Double mucluong) {
		this.mucluong = mucluong;
	}

	@Column(name = "TenDN", length = 50)
	public String getTenDn() {
		return this.tenDn;
	}

	public void setTenDn(String tenDn) {
		this.tenDn = tenDn;
	}

	@Column(name = "Matkhau", length = 50)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "Noilamviec", length = 50)
	public String getNoilamviec() {
		return this.noilamviec;
	}

	public void setNoilamviec(String noilamviec) {
		this.noilamviec = noilamviec;
	}

	@Column(name = "Trangthai", length = 50)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "Ghichu", length = 500)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Xuatkho> getXuatkhos() {
		return this.xuatkhos;
	}

	public void setXuatkhos(Set<Xuatkho> xuatkhos) {
		this.xuatkhos = xuatkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Nhapkho> getNhapkhos() {
		return this.nhapkhos;
	}

	public void setNhapkhos(Set<Nhapkho> nhapkhos) {
		this.nhapkhos = nhapkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<NhatkyHang> getNhatkyHangs() {
		return this.nhatkyHangs;
	}

	public void setNhatkyHangs(Set<NhatkyHang> nhatkyHangs) {
		this.nhatkyHangs = nhatkyHangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<NhatkyLh> getNhatkyLhs() {
		return this.nhatkyLhs;
	}

	public void setNhatkyLhs(Set<NhatkyLh> nhatkyLhs) {
		this.nhatkyLhs = nhatkyLhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Lophoc> getLophocs() {
		return this.lophocs;
	}

	public void setLophocs(Set<Lophoc> lophocs) {
		this.lophocs = lophocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Nhatky> getNhatkies() {
		return this.nhatkies;
	}

	public void setNhatkies(Set<Nhatky> nhatkies) {
		this.nhatkies = nhatkies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<NhapkhoNb> getNhapkhoNbs() {
		return this.nhapkhoNbs;
	}

	public void setNhapkhoNbs(Set<NhapkhoNb> nhapkhoNbs) {
		this.nhapkhoNbs = nhapkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<XuatkhoNb> getXuatkhoNbs() {
		return this.xuatkhoNbs;
	}

	public void setXuatkhoNbs(Set<XuatkhoNb> xuatkhoNbs) {
		this.xuatkhoNbs = xuatkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<Nhaplai> getNhaplais() {
		return this.nhaplais;
	}

	public void setNhaplais(Set<Nhaplai> nhaplais) {
		this.nhaplais = nhaplais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaovien")
	public Set<NhatkyGv> getNhatkyGvs() {
		return this.nhatkyGvs;
	}

	public void setNhatkyGvs(Set<NhatkyGv> nhatkyGvs) {
		this.nhatkyGvs = nhatkyGvs;
	}

}
