package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hanghoa generated by hbm2java
 */
@Entity
@Table(name = "Hanghoa", catalog = "Sunshine_final")
public class Hanghoa implements java.io.Serializable {

	private int mahang;
	private BoSp boSp;
	private Danhmuc danhmuc;
	private String tenhang;
	private String dvt;
	private String mota;
	private Integer giaban;
	private String ghichu;
	private Set<ChitietXuatkhoNb> chitietXuatkhoNbs = new HashSet<ChitietXuatkhoNb>(
			0);
	private Set<Tonkho> tonkhos = new HashSet<Tonkho>(0);
	private Set<ChitietXuatkhoNb> chitietXuatkhoNbs_1 = new HashSet<ChitietXuatkhoNb>(
			0);
	private Set<TonghopNxt> tonghopNxts = new HashSet<TonghopNxt>(0);
	private Set<ChitietHanghoa> chitietHanghoas = new HashSet<ChitietHanghoa>(0);
	private Set<ChitietNhaplai> chitietNhaplais = new HashSet<ChitietNhaplai>(0);
	private Set<ChitietXuatkho> chitietXuatkhos = new HashSet<ChitietXuatkho>(0);
	private Set<ChitietNhapkhoNb> chitietNhapkhoNbs = new HashSet<ChitietNhapkhoNb>(
			0);
	private Set<ChitietNhapkho> chitietNhapkhos = new HashSet<ChitietNhapkho>(0);
	private Set<NhatkyHang> nhatkyHangs = new HashSet<NhatkyHang>(0);

	public Hanghoa() {
	}

	public Hanghoa(int mahang, Danhmuc danhmuc) {
		this.mahang = mahang;
		this.danhmuc = danhmuc;
	}

	public Hanghoa(int mahang, BoSp boSp, Danhmuc danhmuc, String tenhang,
			String dvt, String mota, Integer giaban, String ghichu,
			Set<ChitietXuatkhoNb> chitietXuatkhoNbs, Set<Tonkho> tonkhos,
			Set<ChitietXuatkhoNb> chitietXuatkhoNbs_1,
			Set<TonghopNxt> tonghopNxts, Set<ChitietHanghoa> chitietHanghoas,
			Set<ChitietNhaplai> chitietNhaplais,
			Set<ChitietXuatkho> chitietXuatkhos,
			Set<ChitietNhapkhoNb> chitietNhapkhoNbs,
			Set<ChitietNhapkho> chitietNhapkhos, Set<NhatkyHang> nhatkyHangs) {
		this.mahang = mahang;
		this.boSp = boSp;
		this.danhmuc = danhmuc;
		this.tenhang = tenhang;
		this.dvt = dvt;
		this.mota = mota;
		this.giaban = giaban;
		this.ghichu = ghichu;
		this.chitietXuatkhoNbs = chitietXuatkhoNbs;
		this.tonkhos = tonkhos;
		this.chitietXuatkhoNbs_1 = chitietXuatkhoNbs_1;
		this.tonghopNxts = tonghopNxts;
		this.chitietHanghoas = chitietHanghoas;
		this.chitietNhaplais = chitietNhaplais;
		this.chitietXuatkhos = chitietXuatkhos;
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
		this.chitietNhapkhos = chitietNhapkhos;
		this.nhatkyHangs = nhatkyHangs;
	}

	@Id
	@Column(name = "Mahang", unique = true, nullable = false)
	public int getMahang() {
		return this.mahang;
	}

	public void setMahang(int mahang) {
		this.mahang = mahang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaBo")
	public BoSp getBoSp() {
		return this.boSp;
	}

	public void setBoSp(BoSp boSp) {
		this.boSp = boSp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDm", nullable = false)
	public Danhmuc getDanhmuc() {
		return this.danhmuc;
	}

	public void setDanhmuc(Danhmuc danhmuc) {
		this.danhmuc = danhmuc;
	}

	@Column(name = "Tenhang", length = 250)
	public String getTenhang() {
		return this.tenhang;
	}

	public void setTenhang(String tenhang) {
		this.tenhang = tenhang;
	}

	@Column(name = "Dvt", length = 50)
	public String getDvt() {
		return this.dvt;
	}

	public void setDvt(String dvt) {
		this.dvt = dvt;
	}

	@Column(name = "Mota", length = 250)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "Giaban")
	public Integer getGiaban() {
		return this.giaban;
	}

	public void setGiaban(Integer giaban) {
		this.giaban = giaban;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietXuatkhoNb> getChitietXuatkhoNbs() {
		return this.chitietXuatkhoNbs;
	}

	public void setChitietXuatkhoNbs(Set<ChitietXuatkhoNb> chitietXuatkhoNbs) {
		this.chitietXuatkhoNbs = chitietXuatkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<Tonkho> getTonkhos() {
		return this.tonkhos;
	}

	public void setTonkhos(Set<Tonkho> tonkhos) {
		this.tonkhos = tonkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietXuatkhoNb> getChitietXuatkhoNbs_1() {
		return this.chitietXuatkhoNbs_1;
	}

	public void setChitietXuatkhoNbs_1(Set<ChitietXuatkhoNb> chitietXuatkhoNbs_1) {
		this.chitietXuatkhoNbs_1 = chitietXuatkhoNbs_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<TonghopNxt> getTonghopNxts() {
		return this.tonghopNxts;
	}

	public void setTonghopNxts(Set<TonghopNxt> tonghopNxts) {
		this.tonghopNxts = tonghopNxts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietHanghoa> getChitietHanghoas() {
		return this.chitietHanghoas;
	}

	public void setChitietHanghoas(Set<ChitietHanghoa> chitietHanghoas) {
		this.chitietHanghoas = chitietHanghoas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietNhaplai> getChitietNhaplais() {
		return this.chitietNhaplais;
	}

	public void setChitietNhaplais(Set<ChitietNhaplai> chitietNhaplais) {
		this.chitietNhaplais = chitietNhaplais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietXuatkho> getChitietXuatkhos() {
		return this.chitietXuatkhos;
	}

	public void setChitietXuatkhos(Set<ChitietXuatkho> chitietXuatkhos) {
		this.chitietXuatkhos = chitietXuatkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietNhapkhoNb> getChitietNhapkhoNbs() {
		return this.chitietNhapkhoNbs;
	}

	public void setChitietNhapkhoNbs(Set<ChitietNhapkhoNb> chitietNhapkhoNbs) {
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<ChitietNhapkho> getChitietNhapkhos() {
		return this.chitietNhapkhos;
	}

	public void setChitietNhapkhos(Set<ChitietNhapkho> chitietNhapkhos) {
		this.chitietNhapkhos = chitietNhapkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hanghoa")
	public Set<NhatkyHang> getNhatkyHangs() {
		return this.nhatkyHangs;
	}

	public void setNhatkyHangs(Set<NhatkyHang> nhatkyHangs) {
		this.nhatkyHangs = nhatkyHangs;
	}

}
