package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhapkho generated by hbm2java
 */
@Entity
@Table(name = "Nhapkho", catalog = "Sunshine_final")
public class Nhapkho implements java.io.Serializable {

	private int malo;
	private Kho kho;
	private Giaovien giaovien;
	private NhaCc nhaCc;
	private Date ngaynhap;
	private String soCt;
	private int tongtien;
	private String ghichu;
	private Set<ChitietNhaplai> chitietNhaplais = new HashSet<ChitietNhaplai>(0);
	private Set<ChitietXuatkho> chitietXuatkhos = new HashSet<ChitietXuatkho>(0);
	private Set<ChitietNhapkho> chitietNhapkhos = new HashSet<ChitietNhapkho>(0);
	private Set<ChitietXuatkhoNb> chitietXuatkhoNbs = new HashSet<ChitietXuatkhoNb>(
			0);
	private Set<ChitietNhapkhoNb> chitietNhapkhoNbs = new HashSet<ChitietNhapkhoNb>(
			0);
	private Set<Tonkho> tonkhos = new HashSet<Tonkho>(0);
	private Set<ChitietHanghoa> chitietHanghoas = new HashSet<ChitietHanghoa>(0);

	public Nhapkho() {
	}

	public Nhapkho(int malo, Kho kho, Giaovien giaovien, NhaCc nhaCc,
			Date ngaynhap, String soCt, int tongtien) {
		this.malo = malo;
		this.kho = kho;
		this.giaovien = giaovien;
		this.nhaCc = nhaCc;
		this.ngaynhap = ngaynhap;
		this.soCt = soCt;
		this.tongtien = tongtien;
	}

	public Nhapkho(int malo, Kho kho, Giaovien giaovien, NhaCc nhaCc,
			Date ngaynhap, String soCt, int tongtien, String ghichu,
			Set<ChitietNhaplai> chitietNhaplais,
			Set<ChitietXuatkho> chitietXuatkhos,
			Set<ChitietNhapkho> chitietNhapkhos,
			Set<ChitietXuatkhoNb> chitietXuatkhoNbs,
			Set<ChitietNhapkhoNb> chitietNhapkhoNbs, Set<Tonkho> tonkhos,
			Set<ChitietHanghoa> chitietHanghoas) {
		this.malo = malo;
		this.kho = kho;
		this.giaovien = giaovien;
		this.nhaCc = nhaCc;
		this.ngaynhap = ngaynhap;
		this.soCt = soCt;
		this.tongtien = tongtien;
		this.ghichu = ghichu;
		this.chitietNhaplais = chitietNhaplais;
		this.chitietXuatkhos = chitietXuatkhos;
		this.chitietNhapkhos = chitietNhapkhos;
		this.chitietXuatkhoNbs = chitietXuatkhoNbs;
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
		this.tonkhos = tonkhos;
		this.chitietHanghoas = chitietHanghoas;
	}

	@Id
	@Column(name = "Malo", unique = true, nullable = false)
	public int getMalo() {
		return this.malo;
	}

	public void setMalo(int malo) {
		this.malo = malo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Makho", nullable = false)
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGv", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNcc", nullable = false)
	public NhaCc getNhaCc() {
		return this.nhaCc;
	}

	public void setNhaCc(NhaCc nhaCc) {
		this.nhaCc = nhaCc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngaynhap", nullable = false, length = 23)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@Column(name = "SoCT", nullable = false, length = 250)
	public String getSoCt() {
		return this.soCt;
	}

	public void setSoCt(String soCt) {
		this.soCt = soCt;
	}

	@Column(name = "Tongtien", nullable = false)
	public int getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(int tongtien) {
		this.tongtien = tongtien;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietNhaplai> getChitietNhaplais() {
		return this.chitietNhaplais;
	}

	public void setChitietNhaplais(Set<ChitietNhaplai> chitietNhaplais) {
		this.chitietNhaplais = chitietNhaplais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietXuatkho> getChitietXuatkhos() {
		return this.chitietXuatkhos;
	}

	public void setChitietXuatkhos(Set<ChitietXuatkho> chitietXuatkhos) {
		this.chitietXuatkhos = chitietXuatkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietNhapkho> getChitietNhapkhos() {
		return this.chitietNhapkhos;
	}

	public void setChitietNhapkhos(Set<ChitietNhapkho> chitietNhapkhos) {
		this.chitietNhapkhos = chitietNhapkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietXuatkhoNb> getChitietXuatkhoNbs() {
		return this.chitietXuatkhoNbs;
	}

	public void setChitietXuatkhoNbs(Set<ChitietXuatkhoNb> chitietXuatkhoNbs) {
		this.chitietXuatkhoNbs = chitietXuatkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietNhapkhoNb> getChitietNhapkhoNbs() {
		return this.chitietNhapkhoNbs;
	}

	public void setChitietNhapkhoNbs(Set<ChitietNhapkhoNb> chitietNhapkhoNbs) {
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<Tonkho> getTonkhos() {
		return this.tonkhos;
	}

	public void setTonkhos(Set<Tonkho> tonkhos) {
		this.tonkhos = tonkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkho")
	public Set<ChitietHanghoa> getChitietHanghoas() {
		return this.chitietHanghoas;
	}

	public void setChitietHanghoas(Set<ChitietHanghoa> chitietHanghoas) {
		this.chitietHanghoas = chitietHanghoas;
	}

}
