package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhatkyHang generated by hbm2java
 */
@Entity
@Table(name = "NhatkyHang", catalog = "Sunshine_final")
public class NhatkyHang implements java.io.Serializable {

	private int maNk;
	private Giaovien giaovien;
	private Hanghoa hanghoa;
	private String noidung;
	private Date ngayghi;

	public NhatkyHang() {
	}

	public NhatkyHang(int maNk, Giaovien giaovien, Hanghoa hanghoa,
			String noidung, Date ngayghi) {
		this.maNk = maNk;
		this.giaovien = giaovien;
		this.hanghoa = hanghoa;
		this.noidung = noidung;
		this.ngayghi = ngayghi;
	}

	@Id
	@Column(name = "MaNk", unique = true, nullable = false)
	public int getMaNk() {
		return this.maNk;
	}

	public void setMaNk(int maNk) {
		this.maNk = maNk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGv", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mahang", nullable = false)
	public Hanghoa getHanghoa() {
		return this.hanghoa;
	}

	public void setHanghoa(Hanghoa hanghoa) {
		this.hanghoa = hanghoa;
	}

	@Column(name = "Noidung", nullable = false, length = 250)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayghi", nullable = false, length = 23)
	public Date getNgayghi() {
		return this.ngayghi;
	}

	public void setNgayghi(Date ngayghi) {
		this.ngayghi = ngayghi;
	}

}
