package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhatkyGv generated by hbm2java
 */
@Entity
@Table(name = "NhatkyGV", catalog = "Sunshine_final")
public class NhatkyGv implements java.io.Serializable {

	private int maNk;
	private Giaovien giaovien;
	private Date ngayghi;
	private String noidung;

	public NhatkyGv() {
	}

	public NhatkyGv(int maNk, Giaovien giaovien) {
		this.maNk = maNk;
		this.giaovien = giaovien;
	}

	public NhatkyGv(int maNk, Giaovien giaovien, Date ngayghi, String noidung) {
		this.maNk = maNk;
		this.giaovien = giaovien;
		this.ngayghi = ngayghi;
		this.noidung = noidung;
	}

	@Id
	@Column(name = "MaNK", unique = true, nullable = false)
	public int getMaNk() {
		return this.maNk;
	}

	public void setMaNk(int maNk) {
		this.maNk = maNk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGV", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayghi", length = 23)
	public Date getNgayghi() {
		return this.ngayghi;
	}

	public void setNgayghi(Date ngayghi) {
		this.ngayghi = ngayghi;
	}

	@Column(name = "Noidung", length = 500)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
