package entities;

// Generated Nov 23, 2015 4:06:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhom generated by hbm2java
 */
@Entity
@Table(name = "Nhom", catalog = "Sunshine_final")
public class Nhom implements java.io.Serializable {

	private int maNhom;
	private Quyen quyen;
	private String tenNhom;
	private String mota;
	private Set<Giaovien> giaoviens = new HashSet<Giaovien>(0);

	public Nhom() {
	}

	public Nhom(int maNhom, Quyen quyen, String tenNhom) {
		this.maNhom = maNhom;
		this.quyen = quyen;
		this.tenNhom = tenNhom;
	}

	public Nhom(int maNhom, Quyen quyen, String tenNhom, String mota,
			Set<Giaovien> giaoviens) {
		this.maNhom = maNhom;
		this.quyen = quyen;
		this.tenNhom = tenNhom;
		this.mota = mota;
		this.giaoviens = giaoviens;
	}

	@Id
	@Column(name = "MaNhom", unique = true, nullable = false)
	public int getMaNhom() {
		return this.maNhom;
	}

	public void setMaNhom(int maNhom) {
		this.maNhom = maNhom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaQuyen", nullable = false)
	public Quyen getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Quyen quyen) {
		this.quyen = quyen;
	}

	@Column(name = "TenNhom", nullable = false, length = 50)
	public String getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(String tenNhom) {
		this.tenNhom = tenNhom;
	}

	@Column(name = "Mota", length = 10)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhom")
	public Set<Giaovien> getGiaoviens() {
		return this.giaoviens;
	}

	public void setGiaoviens(Set<Giaovien> giaoviens) {
		this.giaoviens = giaoviens;
	}

}
