package entities;

// Generated Nov 27, 2015 10:37:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiemHsId generated by hbm2java
 */
@Embeddable
public class DiemHsId implements java.io.Serializable {

	private int maGd;
	private int maLop;
	private int maHs;

	public DiemHsId() {
	}

	public DiemHsId(int maGd, int maLop, int maHs) {
		this.maGd = maGd;
		this.maLop = maLop;
		this.maHs = maHs;
	}

	@Column(name = "MaGD", nullable = false)
	public int getMaGd() {
		return this.maGd;
	}

	public void setMaGd(int maGd) {
		this.maGd = maGd;
	}

	@Column(name = "MaLop", nullable = false)
	public int getMaLop() {
		return this.maLop;
	}

	public void setMaLop(int maLop) {
		this.maLop = maLop;
	}

	@Column(name = "MaHS", nullable = false)
	public int getMaHs() {
		return this.maHs;
	}

	public void setMaHs(int maHs) {
		this.maHs = maHs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiemHsId))
			return false;
		DiemHsId castOther = (DiemHsId) other;

		return (this.getMaGd() == castOther.getMaGd())
				&& (this.getMaLop() == castOther.getMaLop())
				&& (this.getMaHs() == castOther.getMaHs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaGd();
		result = 37 * result + this.getMaLop();
		result = 37 * result + this.getMaHs();
		return result;
	}

}
