package entities;

// Generated Nov 27, 2015 10:37:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Giaidoan generated by hbm2java
 */
@Entity
@Table(name = "Giaidoan", catalog = "Sunshine_final")
public class Giaidoan implements java.io.Serializable {

	private int maGd;
	private String tenGd;
	private String mota;
	private String ghichu;
	private Set<DiemHs> diemHses = new HashSet<DiemHs>(0);

	public Giaidoan() {
	}

	public Giaidoan(int maGd, String tenGd) {
		this.maGd = maGd;
		this.tenGd = tenGd;
	}

	public Giaidoan(int maGd, String tenGd, String mota, String ghichu,
			Set<DiemHs> diemHses) {
		this.maGd = maGd;
		this.tenGd = tenGd;
		this.mota = mota;
		this.ghichu = ghichu;
		this.diemHses = diemHses;
	}

	@Id
	@Column(name = "MaGD", unique = true, nullable = false)
	public int getMaGd() {
		return this.maGd;
	}

	public void setMaGd(int maGd) {
		this.maGd = maGd;
	}

	@Column(name = "TenGD", nullable = false, length = 50)
	public String getTenGd() {
		return this.tenGd;
	}

	public void setTenGd(String tenGd) {
		this.tenGd = tenGd;
	}

	@Column(name = "Mota", length = 50)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "Ghichu", length = 50)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giaidoan")
	public Set<DiemHs> getDiemHses() {
		return this.diemHses;
	}

	public void setDiemHses(Set<DiemHs> diemHses) {
		this.diemHses = diemHses;
	}

}
