package entities;

// Generated Nov 27, 2015 10:37:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KieuQuanhe generated by hbm2java
 */
@Entity
@Table(name = "KieuQuanhe", catalog = "Sunshine_final")
public class KieuQuanhe implements java.io.Serializable {

	private int maQh;
	private String tenQh;
	private String ghichu;
	private Set<Quanhe> quanhes = new HashSet<Quanhe>(0);

	public KieuQuanhe() {
	}

	public KieuQuanhe(int maQh, String tenQh) {
		this.maQh = maQh;
		this.tenQh = tenQh;
	}

	public KieuQuanhe(int maQh, String tenQh, String ghichu, Set<Quanhe> quanhes) {
		this.maQh = maQh;
		this.tenQh = tenQh;
		this.ghichu = ghichu;
		this.quanhes = quanhes;
	}

	@Id
	@Column(name = "MaQH", unique = true, nullable = false)
	public int getMaQh() {
		return this.maQh;
	}

	public void setMaQh(int maQh) {
		this.maQh = maQh;
	}

	@Column(name = "TenQH", nullable = false, length = 50)
	public String getTenQh() {
		return this.tenQh;
	}

	public void setTenQh(String tenQh) {
		this.tenQh = tenQh;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kieuQuanhe")
	public Set<Quanhe> getQuanhes() {
		return this.quanhes;
	}

	public void setQuanhes(Set<Quanhe> quanhes) {
		this.quanhes = quanhes;
	}

}
