package entities;

// Generated Nov 27, 2015 10:37:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhapkhoNb generated by hbm2java
 */
@Entity
@Table(name = "NhapkhoNB", catalog = "Sunshine_final")
public class NhapkhoNb implements java.io.Serializable {

	private int maPn;
	private Giaovien giaovien;
	private Kho khoByKhonhap;
	private Kho khoByKhoxuat;
	private NhaCc nhaCc;
	private Date ngaynhap;
	private String soCt;
	private String ghichu;
	private Set<ChitietNhapkhoNb> chitietNhapkhoNbs = new HashSet<ChitietNhapkhoNb>(
			0);

	public NhapkhoNb() {
	}

	public NhapkhoNb(int maPn, Giaovien giaovien, Kho khoByKhonhap,
			Kho khoByKhoxuat, NhaCc nhaCc, Date ngaynhap, String soCt) {
		this.maPn = maPn;
		this.giaovien = giaovien;
		this.khoByKhonhap = khoByKhonhap;
		this.khoByKhoxuat = khoByKhoxuat;
		this.nhaCc = nhaCc;
		this.ngaynhap = ngaynhap;
		this.soCt = soCt;
	}

	public NhapkhoNb(int maPn, Giaovien giaovien, Kho khoByKhonhap,
			Kho khoByKhoxuat, NhaCc nhaCc, Date ngaynhap, String soCt,
			String ghichu, Set<ChitietNhapkhoNb> chitietNhapkhoNbs) {
		this.maPn = maPn;
		this.giaovien = giaovien;
		this.khoByKhonhap = khoByKhonhap;
		this.khoByKhoxuat = khoByKhoxuat;
		this.nhaCc = nhaCc;
		this.ngaynhap = ngaynhap;
		this.soCt = soCt;
		this.ghichu = ghichu;
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
	}

	@Id
	@Column(name = "MaPn", unique = true, nullable = false)
	public int getMaPn() {
		return this.maPn;
	}

	public void setMaPn(int maPn) {
		this.maPn = maPn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGv", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Khonhap", nullable = false)
	public Kho getKhoByKhonhap() {
		return this.khoByKhonhap;
	}

	public void setKhoByKhonhap(Kho khoByKhonhap) {
		this.khoByKhonhap = khoByKhonhap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Khoxuat", nullable = false)
	public Kho getKhoByKhoxuat() {
		return this.khoByKhoxuat;
	}

	public void setKhoByKhoxuat(Kho khoByKhoxuat) {
		this.khoByKhoxuat = khoByKhoxuat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Khoxuat", nullable = false, insertable = false, updatable = false)
	public NhaCc getNhaCc() {
		return this.nhaCc;
	}

	public void setNhaCc(NhaCc nhaCc) {
		this.nhaCc = nhaCc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngaynhap", nullable = false, length = 23)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@Column(name = "SoCt", nullable = false, length = 250)
	public String getSoCt() {
		return this.soCt;
	}

	public void setSoCt(String soCt) {
		this.soCt = soCt;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhapkhoNb")
	public Set<ChitietNhapkhoNb> getChitietNhapkhoNbs() {
		return this.chitietNhapkhoNbs;
	}

	public void setChitietNhapkhoNbs(Set<ChitietNhapkhoNb> chitietNhapkhoNbs) {
		this.chitietNhapkhoNbs = chitietNhapkhoNbs;
	}

}
