package entities;

// Generated Nov 27, 2015 10:37:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhaplai generated by hbm2java
 */
@Entity
@Table(name = "Nhaplai", catalog = "Sunshine_final")
public class Nhaplai implements java.io.Serializable {

	private int maPn;
	private Kho kho;
	private Giaovien giaovien;
	private Date ngaynhap;
	private int tongtien;
	private String soCt;
	private String ghichu;
	private Set<ChitietNhaplai> chitietNhaplais = new HashSet<ChitietNhaplai>(0);

	public Nhaplai() {
	}

	public Nhaplai(int maPn, Kho kho, Giaovien giaovien, Date ngaynhap,
			int tongtien, String soCt) {
		this.maPn = maPn;
		this.kho = kho;
		this.giaovien = giaovien;
		this.ngaynhap = ngaynhap;
		this.tongtien = tongtien;
		this.soCt = soCt;
	}

	public Nhaplai(int maPn, Kho kho, Giaovien giaovien, Date ngaynhap,
			int tongtien, String soCt, String ghichu,
			Set<ChitietNhaplai> chitietNhaplais) {
		this.maPn = maPn;
		this.kho = kho;
		this.giaovien = giaovien;
		this.ngaynhap = ngaynhap;
		this.tongtien = tongtien;
		this.soCt = soCt;
		this.ghichu = ghichu;
		this.chitietNhaplais = chitietNhaplais;
	}

	@Id
	@Column(name = "MaPn", unique = true, nullable = false)
	public int getMaPn() {
		return this.maPn;
	}

	public void setMaPn(int maPn) {
		this.maPn = maPn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Makho", nullable = false)
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaGv", nullable = false)
	public Giaovien getGiaovien() {
		return this.giaovien;
	}

	public void setGiaovien(Giaovien giaovien) {
		this.giaovien = giaovien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngaynhap", nullable = false, length = 23)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@Column(name = "Tongtien", nullable = false)
	public int getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(int tongtien) {
		this.tongtien = tongtien;
	}

	@Column(name = "SoCT", nullable = false, length = 50)
	public String getSoCt() {
		return this.soCt;
	}

	public void setSoCt(String soCt) {
		this.soCt = soCt;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhaplai")
	public Set<ChitietNhaplai> getChitietNhaplais() {
		return this.chitietNhaplais;
	}

	public void setChitietNhaplais(Set<ChitietNhaplai> chitietNhaplais) {
		this.chitietNhaplais = chitietNhaplais;
	}

}
