package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietHanghoaId generated by hbm2java
 */
@Embeddable
public class ChitietHanghoaId implements java.io.Serializable {

	private int malo;
	private int mahang;

	public ChitietHanghoaId() {
	}

	public ChitietHanghoaId(int malo, int mahang) {
		this.malo = malo;
		this.mahang = mahang;
	}

	@Column(name = "Malo", nullable = false)
	public int getMalo() {
		return this.malo;
	}

	public void setMalo(int malo) {
		this.malo = malo;
	}

	@Column(name = "Mahang", nullable = false)
	public int getMahang() {
		return this.mahang;
	}

	public void setMahang(int mahang) {
		this.mahang = mahang;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitietHanghoaId))
			return false;
		ChitietHanghoaId castOther = (ChitietHanghoaId) other;

		return (this.getMalo() == castOther.getMalo())
				&& (this.getMahang() == castOther.getMahang());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMalo();
		result = 37 * result + this.getMahang();
		return result;
	}

}
