package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", catalog = "Sunshine_final")
public class Users implements java.io.Serializable {

	private int maGv;
	private String tenDn;
	private String matkhau;
	private Integer maNhom;

	public Users() {
	}

	public Users(int maGv) {
		this.maGv = maGv;
	}

	public Users(int maGv, String tenDn, String matkhau, Integer maNhom) {
		this.maGv = maGv;
		this.tenDn = tenDn;
		this.matkhau = matkhau;
		this.maNhom = maNhom;
	}

	@Id
	@Column(name = "MaGV", unique = true, nullable = false)
	public int getMaGv() {
		return this.maGv;
	}

	public void setMaGv(int maGv) {
		this.maGv = maGv;
	}

	@Column(name = "TenDN", length = 50)
	public String getTenDn() {
		return this.tenDn;
	}

	public void setTenDn(String tenDn) {
		this.tenDn = tenDn;
	}

	@Column(name = "Matkhau", length = 20)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "MaNhom")
	public Integer getMaNhom() {
		return this.maNhom;
	}

	public void setMaNhom(Integer maNhom) {
		this.maNhom = maNhom;
	}

}
