package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChitietHanghoa generated by hbm2java
 */
@Entity
@Table(name = "ChitietHanghoa", catalog = "Sunshine_final")
public class ChitietHanghoa implements java.io.Serializable {

	private ChitietHanghoaId id;
	private Hanghoa hanghoa;
	private Nhapkho nhapkho;
	private int gianhap;
	private Integer giaban;
	private String ghichu;

	public ChitietHanghoa() {
	}

	public ChitietHanghoa(ChitietHanghoaId id, Hanghoa hanghoa,
			Nhapkho nhapkho, int gianhap) {
		this.id = id;
		this.hanghoa = hanghoa;
		this.nhapkho = nhapkho;
		this.gianhap = gianhap;
	}

	public ChitietHanghoa(ChitietHanghoaId id, Hanghoa hanghoa,
			Nhapkho nhapkho, int gianhap, Integer giaban, String ghichu) {
		this.id = id;
		this.hanghoa = hanghoa;
		this.nhapkho = nhapkho;
		this.gianhap = gianhap;
		this.giaban = giaban;
		this.ghichu = ghichu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "malo", column = @Column(name = "Malo", nullable = false)),
			@AttributeOverride(name = "mahang", column = @Column(name = "Mahang", nullable = false)) })
	public ChitietHanghoaId getId() {
		return this.id;
	}

	public void setId(ChitietHanghoaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mahang", nullable = false, insertable = false, updatable = false)
	public Hanghoa getHanghoa() {
		return this.hanghoa;
	}

	public void setHanghoa(Hanghoa hanghoa) {
		this.hanghoa = hanghoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Malo", nullable = false, insertable = false, updatable = false)
	public Nhapkho getNhapkho() {
		return this.nhapkho;
	}

	public void setNhapkho(Nhapkho nhapkho) {
		this.nhapkho = nhapkho;
	}

	@Column(name = "Gianhap", nullable = false)
	public int getGianhap() {
		return this.gianhap;
	}

	public void setGianhap(int gianhap) {
		this.gianhap = gianhap;
	}

	@Column(name = "Giaban")
	public Integer getGiaban() {
		return this.giaban;
	}

	public void setGiaban(Integer giaban) {
		this.giaban = giaban;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
