package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * Hocsinh generated by hbm2java
 */
@Entity
@Table(name = "Hocsinh", catalog = "Sunshine_final")
@XmlRootElement
public class Hocsinh implements java.io.Serializable {

	private int maHs;
	private Doituong doituong;
	private ChitietHs chitietHs;
	private Lophoc lophoc;
	private String hoten;
	private String ten;
	private String gioitinh;
	private Date namsinh;
	private Date ngayvao;
	private String trangthai;
	private String ghichu;
	private byte[] image;
	private Set<Quanhe> quanhesForMaHs01 = new HashSet<Quanhe>(0);
	private Set<Nhatky> nhatkies = new HashSet<Nhatky>(0);
	private Set<ChitietXuatkho> chitietXuatkhos = new HashSet<ChitietXuatkho>(0);
	private Set<Lopdahoc> lopdahocs = new HashSet<Lopdahoc>(0);
	private Set<ChitietNhaplai> chitietNhaplais = new HashSet<ChitietNhaplai>(0);
	private Set<Hocphi> hocphis = new HashSet<Hocphi>(0);
	private Set<ChitietLop> chitietLops = new HashSet<ChitietLop>(0);
	private Set<DiemHs> diemHses = new HashSet<DiemHs>(0);
	private Set<Quanhe> quanhesForMaHs02 = new HashSet<Quanhe>(0);

	public Hocsinh() {
	}

	public Hocsinh(int maHs) {
		this.maHs = maHs;
	}

	public Hocsinh(int maHs, Doituong doituong, ChitietHs chitietHs,
			Lophoc lophoc, String hoten, String ten, String gioitinh,
			Date namsinh, Date ngayvao, String trangthai, String ghichu,
			byte[] image, Set<Quanhe> quanhesForMaHs01, Set<Nhatky> nhatkies,
			Set<ChitietXuatkho> chitietXuatkhos, Set<Lopdahoc> lopdahocs,
			Set<ChitietNhaplai> chitietNhaplais, Set<Hocphi> hocphis,
			Set<ChitietLop> chitietLops, Set<DiemHs> diemHses,
			Set<Quanhe> quanhesForMaHs02) {
		this.maHs = maHs;
		this.doituong = doituong;
		this.chitietHs = chitietHs;
		this.lophoc = lophoc;
		this.hoten = hoten;
		this.ten = ten;
		this.gioitinh = gioitinh;
		this.namsinh = namsinh;
		this.ngayvao = ngayvao;
		this.trangthai = trangthai;
		this.ghichu = ghichu;
		this.image = image;
		this.quanhesForMaHs01 = quanhesForMaHs01;
		this.nhatkies = nhatkies;
		this.chitietXuatkhos = chitietXuatkhos;
		this.lopdahocs = lopdahocs;
		this.chitietNhaplais = chitietNhaplais;
		this.hocphis = hocphis;
		this.chitietLops = chitietLops;
		this.diemHses = diemHses;
		this.quanhesForMaHs02 = quanhesForMaHs02;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaHS", unique = true, nullable = false)
	public int getMaHs() {
		return this.maHs;
	}

	public void setMaHs(int maHs) {
		this.maHs = maHs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDT")
	public Doituong getDoituong() {
		return this.doituong;
	}

	public void setDoituong(Doituong doituong) {
		this.doituong = doituong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaBM")
	public ChitietHs getChitietHs() {
		return this.chitietHs;
	}

	public void setChitietHs(ChitietHs chitietHs) {
		this.chitietHs = chitietHs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLop")
	public Lophoc getLophoc() {
		return this.lophoc;
	}

	public void setLophoc(Lophoc lophoc) {
		this.lophoc = lophoc;
	}

	@Column(name = "Hoten", length = 250)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "Ten", length = 250)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "Gioitinh", length = 10)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Namsinh", length = 23)
	public Date getNamsinh() {
		return this.namsinh;
	}

	public void setNamsinh(Date namsinh) {
		this.namsinh = namsinh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayvao", length = 23)
	public Date getNgayvao() {
		return this.ngayvao;
	}

	public void setNgayvao(Date ngayvao) {
		this.ngayvao = ngayvao;
	}

	@Column(name = "Trangthai", length = 50)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "Ghichu", length = 500)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "Image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinhByMaHs01")
	public Set<Quanhe> getQuanhesForMaHs01() {
		return this.quanhesForMaHs01;
	}

	public void setQuanhesForMaHs01(Set<Quanhe> quanhesForMaHs01) {
		this.quanhesForMaHs01 = quanhesForMaHs01;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Nhatky> getNhatkies() {
		return this.nhatkies;
	}

	public void setNhatkies(Set<Nhatky> nhatkies) {
		this.nhatkies = nhatkies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<ChitietXuatkho> getChitietXuatkhos() {
		return this.chitietXuatkhos;
	}

	public void setChitietXuatkhos(Set<ChitietXuatkho> chitietXuatkhos) {
		this.chitietXuatkhos = chitietXuatkhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Lopdahoc> getLopdahocs() {
		return this.lopdahocs;
	}

	public void setLopdahocs(Set<Lopdahoc> lopdahocs) {
		this.lopdahocs = lopdahocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<ChitietNhaplai> getChitietNhaplais() {
		return this.chitietNhaplais;
	}

	public void setChitietNhaplais(Set<ChitietNhaplai> chitietNhaplais) {
		this.chitietNhaplais = chitietNhaplais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<Hocphi> getHocphis() {
		return this.hocphis;
	}

	public void setHocphis(Set<Hocphi> hocphis) {
		this.hocphis = hocphis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<ChitietLop> getChitietLops() {
		return this.chitietLops;
	}

	public void setChitietLops(Set<ChitietLop> chitietLops) {
		this.chitietLops = chitietLops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinh")
	public Set<DiemHs> getDiemHses() {
		return this.diemHses;
	}

	public void setDiemHses(Set<DiemHs> diemHses) {
		this.diemHses = diemHses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocsinhByMaHs02")
	public Set<Quanhe> getQuanhesForMaHs02() {
		return this.quanhesForMaHs02;
	}

	public void setQuanhesForMaHs02(Set<Quanhe> quanhesForMaHs02) {
		this.quanhesForMaHs02 = quanhesForMaHs02;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.hoten + " " + this.ten;
	}

}
