package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kiemkho generated by hbm2java
 */
@Entity
@Table(name = "Kiemkho", catalog = "Sunshine_final")
public class Kiemkho implements java.io.Serializable {

	private int maKh;
	private Date ngayluu;
	private int malo;
	private int mahang;
	private int soluong;
	private int maKho;
	private Integer ghichu;

	public Kiemkho() {
	}

	public Kiemkho(int maKh, Date ngayluu, int malo, int mahang, int soluong,
			int maKho) {
		this.maKh = maKh;
		this.ngayluu = ngayluu;
		this.malo = malo;
		this.mahang = mahang;
		this.soluong = soluong;
		this.maKho = maKho;
	}

	public Kiemkho(int maKh, Date ngayluu, int malo, int mahang, int soluong,
			int maKho, Integer ghichu) {
		this.maKh = maKh;
		this.ngayluu = ngayluu;
		this.malo = malo;
		this.mahang = mahang;
		this.soluong = soluong;
		this.maKho = maKho;
		this.ghichu = ghichu;
	}

	@Id
	@Column(name = "MaKh", unique = true, nullable = false)
	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ngayluu", nullable = false, length = 23)
	public Date getNgayluu() {
		return this.ngayluu;
	}

	public void setNgayluu(Date ngayluu) {
		this.ngayluu = ngayluu;
	}

	@Column(name = "Malo", nullable = false)
	public int getMalo() {
		return this.malo;
	}

	public void setMalo(int malo) {
		this.malo = malo;
	}

	@Column(name = "Mahang", nullable = false)
	public int getMahang() {
		return this.mahang;
	}

	public void setMahang(int mahang) {
		this.mahang = mahang;
	}

	@Column(name = "Soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Column(name = "MaKho", nullable = false)
	public int getMaKho() {
		return this.maKho;
	}

	public void setMaKho(int maKho) {
		this.maKho = maKho;
	}

	@Column(name = "Ghichu")
	public Integer getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(Integer ghichu) {
		this.ghichu = ghichu;
	}

}
