package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lopdahoc generated by hbm2java
 */
@Entity
@Table(name = "Lopdahoc", catalog = "Sunshine_final")
public class Lopdahoc implements java.io.Serializable {

	private LopdahocId id;
	private Hocsinh hocsinh;
	private Lophoc lophoc;
	private String ghichu;

	public Lopdahoc() {
	}

	public Lopdahoc(LopdahocId id, Hocsinh hocsinh, Lophoc lophoc) {
		this.id = id;
		this.hocsinh = hocsinh;
		this.lophoc = lophoc;
	}

	public Lopdahoc(LopdahocId id, Hocsinh hocsinh, Lophoc lophoc, String ghichu) {
		this.id = id;
		this.hocsinh = hocsinh;
		this.lophoc = lophoc;
		this.ghichu = ghichu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "maHs", column = @Column(name = "MaHs", nullable = false)),
			@AttributeOverride(name = "maLop", column = @Column(name = "MaLop", nullable = false)) })
	public LopdahocId getId() {
		return this.id;
	}

	public void setId(LopdahocId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaHs", nullable = false, insertable = false, updatable = false)
	public Hocsinh getHocsinh() {
		return this.hocsinh;
	}

	public void setHocsinh(Hocsinh hocsinh) {
		this.hocsinh = hocsinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLop", nullable = false, insertable = false, updatable = false)
	public Lophoc getLophoc() {
		return this.lophoc;
	}

	public void setLophoc(Lophoc lophoc) {
		this.lophoc = lophoc;
	}

	@Column(name = "Ghichu", length = 250)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
