package entities;

// Generated Dec 17, 2015 9:55:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuanheId generated by hbm2java
 */
@Embeddable
public class QuanheId implements java.io.Serializable {

	private int maHs01;
	private int maHs02;

	public QuanheId() {
	}

	public QuanheId(int maHs01, int maHs02) {
		this.maHs01 = maHs01;
		this.maHs02 = maHs02;
	}

	@Column(name = "MaHS01", nullable = false)
	public int getMaHs01() {
		return this.maHs01;
	}

	public void setMaHs01(int maHs01) {
		this.maHs01 = maHs01;
	}

	@Column(name = "MaHS02", nullable = false)
	public int getMaHs02() {
		return this.maHs02;
	}

	public void setMaHs02(int maHs02) {
		this.maHs02 = maHs02;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuanheId))
			return false;
		QuanheId castOther = (QuanheId) other;

		return (this.getMaHs01() == castOther.getMaHs01())
				&& (this.getMaHs02() == castOther.getMaHs02());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaHs01();
		result = 37 * result + this.getMaHs02();
		return result;
	}

}
