package entities;

// Generated Dec 21, 2015 2:53:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiemId generated by hbm2java
 */
@Embeddable
public class DiemId implements java.io.Serializable {

	private int maMh;
	private int maSv;

	public DiemId() {
	}

	public DiemId(int maMh, int maSv) {
		this.maMh = maMh;
		this.maSv = maSv;
	}

	@Column(name = "MaMH", nullable = false)
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}

	@Column(name = "MaSV", nullable = false)
	public int getMaSv() {
		return this.maSv;
	}

	public void setMaSv(int maSv) {
		this.maSv = maSv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiemId))
			return false;
		DiemId castOther = (DiemId) other;

		return (this.getMaMh() == castOther.getMaMh())
				&& (this.getMaSv() == castOther.getMaSv());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaMh();
		result = 37 * result + this.getMaSv();
		return result;
	}

}
