package entities;

// Generated Dec 21, 2015 2:53:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name = "Monhoc", catalog = "Qlydiem")
@XmlRootElement
public class Monhoc implements java.io.Serializable {

	private int maMh;
	private String tenMh;
	private int sdvht;
	private Set<Diem> diems = new HashSet<Diem>(0);
	private Set<Sinhvien> sinhviens = new HashSet<Sinhvien>(0);

	public Monhoc() {
	}

	public Monhoc(int maMh, String tenMh, int sdvht) {
		this.maMh = maMh;
		this.tenMh = tenMh;
		this.sdvht = sdvht;
	}

	public Monhoc(int maMh, String tenMh, int sdvht, Set<Diem> diems,
			Set<Sinhvien> sinhviens) {
		this.maMh = maMh;
		this.tenMh = tenMh;
		this.sdvht = sdvht;
		this.diems = diems;
		this.sinhviens = sinhviens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaMH", unique = true, nullable = false)
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}

	@Column(name = "TenMH", nullable = false, length = 50)
	public String getTenMh() {
		return this.tenMh;
	}

	public void setTenMh(String tenMh) {
		this.tenMh = tenMh;
	}

	@Column(name = "SDVHT", nullable = false)
	public int getSdvht() {
		return this.sdvht;
	}

	public void setSdvht(int sdvht) {
		this.sdvht = sdvht;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monhoc")
	public Set<Diem> getDiems() {
		return this.diems;
	}

	public void setDiems(Set<Diem> diems) {
		this.diems = diems;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "monhocs")
	public Set<Sinhvien> getSinhviens() {
		return this.sinhviens;
	}

	public void setSinhviens(Set<Sinhvien> sinhviens) {
		this.sinhviens = sinhviens;
	}

}
