package entities;

// Generated Dec 21, 2015 2:53:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name = "Sinhvien", catalog = "Qlydiem")
@XmlRootElement
public class Sinhvien implements java.io.Serializable {

	private int maSv;
	private Lophoc lophoc;
	private String hoten;
	private String ten;
	private String sdt;
	private String email;
	private String diachi;
	private String ghichu;
	private String image;
	@JsonIgnore
	private Set<Monhoc> monhocs = new HashSet<Monhoc>(0);

	public Sinhvien() {
	}

	public Sinhvien(int maSv, String hoten, String ten) {
		this.maSv = maSv;
		this.hoten = hoten;
		this.ten = ten;
	}

	public Sinhvien(int maSv, Lophoc lophoc, String hoten, String ten,
			String sdt, String email, String diachi, String ghichu,
			String image, Set<Monhoc> monhocs) {
		this.maSv = maSv;
		this.lophoc = lophoc;
		this.hoten = hoten;
		this.ten = ten;
		this.sdt = sdt;
		this.email = email;
		this.diachi = diachi;
		this.ghichu = ghichu;
		this.image = image;
		this.monhocs = monhocs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MaSV", unique = true, nullable = false)
	public int getMaSv() {
		return this.maSv;
	}

	public void setMaSv(int maSv) {
		this.maSv = maSv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLop")
	public Lophoc getLophoc() {
		return this.lophoc;
	}

	public void setLophoc(Lophoc lophoc) {
		this.lophoc = lophoc;
	}

	@Column(name = "Hoten", nullable = false, length = 250)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "Ten", nullable = false, length = 50)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "SDT", length = 50)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Diachi")
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "Ghichu")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Sinhvien_Monhoc", catalog = "Qlydiem", joinColumns = { @JoinColumn(name = "MaSV", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "MaMH", nullable = false, updatable = false) })
	public Set<Monhoc> getMonhocs() {
		return this.monhocs;
	}

	public void setMonhocs(Set<Monhoc> monhocs) {
		this.monhocs = monhocs;
	}

}
